name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Supabase CLI cache
        uses: actions/cache@v4
        with:
          path: ~/.npm/_npx
          key: ${{ runner.os }}-supabase-cli-${{ hashFiles('package-lock.json') }}

      - name: Ensure Supabase CLI installed
        run: npx supabase --version

      - name: Generate types
        run: npm run db:gen

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build 